SET FOREIGN_KEY_CHECKS=0;
DELETE FROM billfee where  ;
DELETE FROM bill ;
DELETE FROM billitem ;
DELETE FROM bill ;
DELETE FROM billnumber ;
DELETE FROM billsession ;
DELETE FROM billcomponent ;
DELETE FROM billentry;
SET FOREIGN_KEY_CHECKS=1;